name: Tests 
on: 
  push:
    branches:
      - '*'
      # we don't want to run test suit when pushing to master 
      #   since it will only contain production ready code!
      - '!master'
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/checkout@v2

      - name: Start server
        run: |
          cd fruits-impl
          mvn clean spring-boot:run

      - name: Run Cucumber tests
        run: |
          cd fruits-specs
          mvn test

      - name: Stop servers
        run: |
          docker-compose down
